In [52]:
import pandas as pd
from sqlalchemy import create_engine

In [53]:
data_file = "./data/2021VAERSVAX.csv"
VAERSVAX_data_df = pd.read_csv(data_file)
VAERSVAX_data_df.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,916600,COVID19,MODERNA,037K20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
1,916601,COVID19,MODERNA,025L20A,1,IM,RA,COVID19 (COVID19 (MODERNA))
2,916602,COVID19,PFIZER\BIONTECH,EL1284,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
3,916603,COVID19,MODERNA,unknown,UNK,NaN,NaN,COVID19 (COVID19 (MODERNA))
4,916604,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))

In [54]:
# Create a filtered dataframe from specific columns
del VAERSVAX_data_df['VAX_LOT']
del VAERSVAX_data_df['VAX_NAME']
del VAERSVAX_data_df['VAX_TYPE']
VAERSVAX_data_df.head()

   VAERS_ID         VAX_MANU VAX_DOSE_SERIES VAX_ROUTE VAX_SITE
0    916600          MODERNA               1        IM       LA
1    916601          MODERNA               1        IM       RA
2    916602  PFIZER\BIONTECH               1        IM       LA
3    916603          MODERNA             UNK       NaN      NaN
4    916604          MODERNA               1        IM       LA

In [56]:
VAERSVAX_data_df.dropna(how="any",inplace=True)
VAERSVAX_data_df.head()

   VAERS_ID         VAX_MANU VAX_DOSE_SERIES VAX_ROUTE VAX_SITE
0    916600          MODERNA               1        IM       LA
1    916601          MODERNA               1        IM       RA
2    916602  PFIZER\BIONTECH               1        IM       LA
4    916604          MODERNA               1        IM       LA
5    916606          MODERNA               1        IM       LA

In [57]:
VAERSVAX_data_df = VAERSVAX_data_df.drop_duplicates()
VAERSVAX_data_df.head()

   VAERS_ID         VAX_MANU VAX_DOSE_SERIES VAX_ROUTE VAX_SITE
0    916600          MODERNA               1        IM       LA
1    916601          MODERNA               1        IM       RA
2    916602  PFIZER\BIONTECH               1        IM       LA
4    916604          MODERNA               1        IM       LA
5    916606          MODERNA               1        IM       LA

In [58]:
VAERSVAX = VAERSVAX_data_df.rename(columns={'VAERS_ID':'Patient','VAX_MANU':'Vaccine','VAX_DOSE_SERIES':'Dose','VAX_ROUTE':'Route','VAX_SITE':'Site'})
VAERSVAX

       Patient          Vaccine Dose Route Site
0       916600          MODERNA    1    IM   LA
1       916601          MODERNA    1    IM   RA
2       916602  PFIZER\BIONTECH    1    IM   LA
4       916604          MODERNA    1    IM   LA
5       916606          MODERNA    1    IM   LA
...        ...              ...  ...   ...  ...
34619  1112743          MODERNA    2    IM   LA
34620  1112773          MODERNA    1    IM   LA
34621  1112825          MODERNA    1    IM   LA
34622  1113563          MODERNA    2   SYR   LA
34629  1115348          MODERNA    1    OT   LA

[23421 rows x 5 columns]

In [59]:
VAERSVAX.to_csv('VAERSVAX.csv')

In [60]:
data_file2 = "./data/2021VAERSSYMPTOMS.csv"
VAERSSYMPTOMS_data_df = pd.read_csv(data_file2)
VAERSSYMPTOMS_data_df.head()

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,916600,Dysphagia,23.1,Epiglottitis,23.1,NaN,NaN,NaN,NaN,NaN,NaN
1,916601,Anxiety,23.1,Dyspnoea,23.1,NaN,NaN,NaN,NaN,NaN,NaN
2,916602,Chest discomfort,23.1,Dysphagia,23.1,Pain in extremity,23.1,Visual impairment,23.1,NaN,NaN
3,916603,Dizziness,23.1,Fatigue,23.1,Mobility decreased,23.1,NaN,NaN,NaN,NaN
4,916604,Injection site erythema,23.1,Injection site pruritus,23.1,Injection site swelling,23.1,Injection site warmth,23.1,NaN,NaN

In [61]:
# Create a filtered dataframe from specific columns
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION5']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION4']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION3']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION2']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION1']
VAERSSYMPTOMS_data_df.head()

,VAERS_ID,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916600,Dysphagia,Epiglottitis,NaN,NaN,NaN
1,916601,Anxiety,Dyspnoea,NaN,NaN,NaN
2,916602,Chest discomfort,Dysphagia,Pain in extremity,Visual impairment,NaN
3,916603,Dizziness,Fatigue,Mobility decreased,NaN,NaN
4,916604,Injection site erythema,Injection site pruritus,Injection site swelling,Injection site warmth,NaN

In [62]:
VAERSSYMPTOMS_data_df.dropna(how="all",inplace= True)
VAERSSYMPTOMS_data_df.drop_duplicates()
VAERSSYMPTOMS_data_df

,VAERS_ID,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916600,Dysphagia,Epiglottitis,NaN,NaN,NaN
1,916601,Anxiety,Dyspnoea,NaN,NaN,NaN
2,916602,Chest discomfort,Dysphagia,Pain in extremity,Visual impairment,NaN
3,916603,Dizziness,Fatigue,Mobility decreased,NaN,NaN
4,916604,Injection site erythema,Injection site pruritus,Injection site swelling,Injection site warmth,NaN
...,...,...,...,...,...,...
48105,1113920,Nasal discomfort,Night sweats,Platelet count,Platelet count decreased,Pyrexia
48106,1113920,Rash,SARS-CoV-2 test,NaN,NaN,NaN
48107,1113963,Haemophagocytic lymphohistiocytosis,SARS-CoV-2 test,NaN,NaN,NaN
48108,1115045,Death,NaN,NaN,NaN,NaN
48109,1115348,Death,NaN,NaN,NaN,NaN

In [63]:
VAERSSYMPTOMS = VAERSSYMPTOMS_data_df.rename(columns={'VAERS_ID':'Patient'})
VAERSSYMPTOMS

,Patient,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916600,Dysphagia,Epiglottitis,NaN,NaN,NaN
1,916601,Anxiety,Dyspnoea,NaN,NaN,NaN
2,916602,Chest discomfort,Dysphagia,Pain in extremity,Visual impairment,NaN
3,916603,Dizziness,Fatigue,Mobility decreased,NaN,NaN
4,916604,Injection site erythema,Injection site pruritus,Injection site swelling,Injection site warmth,NaN
...,...,...,...,...,...,...
48105,1113920,Nasal discomfort,Night sweats,Platelet count,Platelet count decreased,Pyrexia
48106,1113920,Rash,SARS-CoV-2 test,NaN,NaN,NaN
48107,1113963,Haemophagocytic lymphohistiocytosis,SARS-CoV-2 test,NaN,NaN,NaN
48108,1115045,Death,NaN,NaN,NaN,NaN
48109,1115348,Death,NaN,NaN,NaN,NaN