In [113]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import create_engine
from config import password

In [114]:
data_file = "./data/2021VAERSVAX.csv"
VAERSVAX_data_df = pd.read_csv(data_file)
VAERSVAX_data_df.head(20)

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,916600,COVID19,MODERNA,037K20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
1,916601,COVID19,MODERNA,025L20A,1,IM,RA,COVID19 (COVID19 (MODERNA))
2,916602,COVID19,PFIZER\BIONTECH,EL1284,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
3,916603,COVID19,MODERNA,unknown,UNK,NaN,NaN,COVID19 (COVID19 (MODERNA))
4,916604,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))
5,916606,COVID19,MODERNA,011J20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
6,916607,COVID19,MODERNA,NaN,UNK,IM,LA,COVID19 (COVID19 (MODERNA))
7,916608,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))
8,916609,COVID19,MODERNA,011J201A,1,IM,LA,COVID19 (COVID19 (MODERNA))
9,916610,COVID19,MODERNA,NaN,1,SYR,LA,COVID19 (COVID19 (MODERNA))
10,916611,COVID19,MODERNA,039k20a,1,SYR,RA,COVID19 (COVID19 (MODERNA))
11,916613,COVID19,MODERNA,025J20-2A,1,SYR,LA,COVID19 (COVID19 (MODERNA))
12,916614,COVID19,MODERNA,011J20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
13,916615,COVID19,MODERNA,025J20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
14,916617,COVID19,PFIZER\BIONTECH,Eh9899,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
15,916618,COVID19,MODERNA,NaN,1,IM,LA,COVID19 (COVID19 (MODERNA))
16,916619,COVID19,PFIZER\BIONTECH,NaN,1,IM,LA,COVID19 (COVID19 (PFIZER-BIONTECH))
17,916620,COVID19,MODERNA,011L20A,1,IM,LA,COVID19 (COVID19 (MODERNA))
18,916621,COVID19,MODERNA,NaN,1,SYR,LA,COVID19 (COVID19 (MODERNA))
19,916622,COVID19,MODERNA,025J20A,1,SYR,LA,COVID19 (COVID19 (MODERNA))

In [115]:
# Create a filtered dataframe from specific columns
del VAERSVAX_data_df['VAX_LOT']
del VAERSVAX_data_df['VAX_NAME']
del VAERSVAX_data_df['VAX_TYPE']
VAERSVAX_data_df.head(100)

    VAERS_ID         VAX_MANU VAX_DOSE_SERIES VAX_ROUTE VAX_SITE
0     916600          MODERNA               1        IM       LA
1     916601          MODERNA               1        IM       RA
2     916602  PFIZER\BIONTECH               1        IM       LA
3     916603          MODERNA             UNK       NaN      NaN
4     916604          MODERNA               1        IM       LA
..       ...              ...             ...       ...      ...
95    916701          MODERNA               1        IM       LA
96    916703          MODERNA               1        IM       LA
97    916704          MODERNA               1        IM       LA
98    916706          MODERNA               1       SYR       LA
99    916707          MODERNA               1        IM       LA

[100 rows x 5 columns]

In [116]:
VAERSVAX_data_df.dropna(how="all",inplace= True)
VAERSVAX_data_df.drop_duplicates()
VAERSVAX_data_df.head(100)

    VAERS_ID         VAX_MANU VAX_DOSE_SERIES VAX_ROUTE VAX_SITE
0     916600          MODERNA               1        IM       LA
1     916601          MODERNA               1        IM       RA
2     916602  PFIZER\BIONTECH               1        IM       LA
3     916603          MODERNA             UNK       NaN      NaN
4     916604          MODERNA               1        IM       LA
..       ...              ...             ...       ...      ...
95    916701          MODERNA               1        IM       LA
96    916703          MODERNA               1        IM       LA
97    916704          MODERNA               1        IM       LA
98    916706          MODERNA               1       SYR       LA
99    916707          MODERNA               1        IM       LA

[100 rows x 5 columns]

In [118]:
VAERSVAX = VAERSVAX_data_df.rename(columns={'VAERS_ID':'Patient','VAX_MANU':'Vaccine','VAX_DOSE_SERIES':'Dose','VAX_ROUTE':'Route','VAX_SITE':'Site'})
VAERSVAX

       Patient          Vaccine Dose Route Site
0       916600          MODERNA    1    IM   LA
1       916601          MODERNA    1    IM   RA
2       916602  PFIZER\BIONTECH    1    IM   LA
3       916603          MODERNA  UNK   NaN  NaN
4       916604          MODERNA    1    IM   LA
...        ...              ...  ...   ...  ...
34625  1113917          MODERNA    1    OT  NaN
34626  1113920  PFIZER\BIONTECH    1   NaN  NaN
34627  1113963  PFIZER\BIONTECH    2   NaN  NaN
34628  1115045          MODERNA    2    OT  NaN
34629  1115348          MODERNA    1    OT   LA

[34630 rows x 5 columns]

In [ ]:
VAERSVAX.to_csv('VAERSVAX.csv')

In [ ]:
#Check for tables
#engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/employee_db')
#engine.table_names()

In [ ]:
#Use pandas to load csv converted DataFrame into database¶
#VAERSVAX.to_sql(name='VAERSVAX', con=engine, if_exists='append', index=False)

In [ ]:
data_file2 = "./data/2021VAERSSYMPTOMS.csv"
VAERSSYMPTOMS_data_df = pd.read_csv(data_file2)
VAERSSYMPTOMS_data_df.head()

In [ ]:
# Create a filtered dataframe from specific columns
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION5']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION4']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION3']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION2']
del VAERSSYMPTOMS_data_df['SYMPTOMVERSION1']
VAERSSYMPTOMS_data_df.head(100)

In [119]:
VAERSSYMPTOMS_data_df.dropna(how="all",inplace= True)
VAERSSYMPTOMS_data_df.drop_duplicates()
VAERSSYMPTOMS_data_df

,VAERS_ID,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916600,Dysphagia,Epiglottitis,NaN,NaN,NaN
1,916601,Anxiety,Dyspnoea,NaN,NaN,NaN
2,916602,Chest discomfort,Dysphagia,Pain in extremity,Visual impairment,NaN
3,916603,Dizziness,Fatigue,Mobility decreased,NaN,NaN
4,916604,Injection site erythema,Injection site pruritus,Injection site swelling,Injection site warmth,NaN
...,...,...,...,...,...,...
48105,1113920,Nasal discomfort,Night sweats,Platelet count,Platelet count decreased,Pyrexia
48106,1113920,Rash,SARS-CoV-2 test,NaN,NaN,NaN
48107,1113963,Haemophagocytic lymphohistiocytosis,SARS-CoV-2 test,NaN,NaN,NaN
48108,1115045,Death,NaN,NaN,NaN,NaN
48109,1115348,Death,NaN,NaN,NaN,NaN

In [120]:
VAERSSYMPTOMS = VAERSSYMPTOMS_data_df.rename(columns={'VAERS_ID':'Patient'})
VAERSSYMPTOMS

,Patient,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5
0,916600,Dysphagia,Epiglottitis,NaN,NaN,NaN
1,916601,Anxiety,Dyspnoea,NaN,NaN,NaN
2,916602,Chest discomfort,Dysphagia,Pain in extremity,Visual impairment,NaN
3,916603,Dizziness,Fatigue,Mobility decreased,NaN,NaN
4,916604,Injection site erythema,Injection site pruritus,Injection site swelling,Injection site warmth,NaN
...,...,...,...,...,...,...
48105,1113920,Nasal discomfort,Night sweats,Platelet count,Platelet count decreased,Pyrexia
48106,1113920,Rash,SARS-CoV-2 test,NaN,NaN,NaN
48107,1113963,Haemophagocytic lymphohistiocytosis,SARS-CoV-2 test,NaN,NaN,NaN
48108,1115045,Death,NaN,NaN,NaN,NaN
48109,1115348,Death,NaN,NaN,NaN,NaN

In [ ]:
#data_file1 = "./data/2021VAERSDATA.csv"
#VAERSDATA_data_df = pd.read_csv(data_file1)
#VAERSDATA_data_df.head()